# Generated by Django 6.0 on 2025-12-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.IntegerField()),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('transactionType', models.CharField(choices=[('withdrawal', 'Withdrawal'), ('deposit', 'Deposit')], max_length=100)),
                ('accountType', models.CharField(max_length=100)),
                ('accountBalance', models.FloatField()),
                ('dateOfAccountOpening', models.DateField()),
                ('lastTransactionDate', models.DateField()),
                ('transactionId', models.IntegerField()),
                ('transactionDate', models.DateField()),
                ('transactionAmount', models.FloatField()),
                ('accountBalanceAfterTransaction', models.FloatField()),
                ('branchId', models.IntegerField()),
                ('loanId', models.IntegerField()),
                ('loanAmount', models.FloatField()),
                ('loanType', models.CharField(max_length=100)),
                ('interestRate', models.FloatField()),
                ('loanTerm', models.IntegerField()),
                ('approvalRejectionDate', models.DateField()),
                ('loanStatus', models.CharField(choices=[('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Closed', 'Closed')], max_length=100)),
                ('cardId', models.IntegerField()),
                ('cardType', models.CharField(max_length=100)),
                ('creditLimit', models.FloatField()),
                ('creditLimitBalance', models.FloatField()),
                ('minimumPaymentDue', models.DateField()),
                ('paymentDueDate', models.DateField()),
                ('lastCreditCardPaymentDate', models.DateField()),
                ('rewardsPoints', models.IntegerField()),
                ('feedbackId', models.IntegerField()),
                ('feedbackDate', models.DateField()),
                ('feedbackType', models.CharField(max_length=100)),
                ('resolutionStatus', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], max_length=100)),
                ('resolutionAmount', models.FloatField()),
                ('resolutionDate', models.DateField()),
                ('anomality', models.FloatField()),
            ],
            options={
                'db_table': 'raw_transactions',
                'managed': False,
            },
        ),
    ]
